### ISSUE TITLE
After I update from 3.8.0 to v3.9.0  I GET ERROR in node_modules/xterm/lib/addons/fit/fit.d.ts(1,23): error TS2688: Cannot find type definition file for '../..'.

### ISSUE THREAD

**Issue by ofirrifo** [xtermjs/xterm.js#1830]
After I update from 3.8.0 to v3.9.0 
I start to get this error:

> ERROR in node_modules/xterm/lib/addons/fit/fit.d.ts(1,23): error TS2688: Cannot find type definition file for '../..'.

on v3.8.0 it work as should.

## Details
- Browser and browser version: 
- OS version: 
- xterm.js version:  v3.9.0

**Comment by Tyriar** [comment]
Root cause https://github.com/xtermjs/xterm.js/pull/1699/commits/33915f3ae0867419b744b49f2a1d7cdc3e5b7f7d from https://github.com/xtermjs/xterm.js/pull/1699

**Comment by ofirrifo** [comment]
thanks for the rapid response
