### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by circuitry2** [xtermjs/xterm.js#1363]
## Details
- Browser and browser version:  Chrome 61
- OS version: 10.12.1
- xterm.js version: latest

### Steps to reproduce

1. git clone https://github.com/xtermjs/xterm.js.git
2. cd xterm.js
3. npm i
4. npm run watch
5. In another terminal "npm start"

When I do this I get:
```
~/Downloads/node_modules/xterm/typings/xterm.d.ts(14,15): error TS2300: Duplicate identifier 'FontWeight'.
~/Downloads/node_modules/xterm/typings/xterm.d.ts(247,16): error TS2300: Duplicate identifier 'Terminal'.
~/Downloads/xterm.js-master/typings/xterm.d.ts(14,15): error TS2300: Duplicate identifier 'FontWeight'.
~/Downloads/xterm.js-master/typings/xterm.d.ts(254,16): error TS2300: Duplicate identifier 'Terminal'.
```

When I open the demo I get the black terminal screen with no text.
In Chrome developer tools I see:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Parser.parse (xterm.js:2280)
    at Terminal._innerWrite (xterm.js:4090)
    at xterm.js:4075
```

Which is coming from:
```
    Parser.prototype.parse = function (data) {
        var l = data.length;
        var cs;
        var ch;

```

**Comment by Tyriar** [comment]
I can repro, must have been caused by a recent push.

**Comment by Tyriar** [comment]
Caused by https://github.com/xtermjs/xterm.js/pull/1355, `undefined` is being written to the terminal.

**Comment by Tyriar** [comment]
Oh JavaScript, you so crazy:

<img width="136" alt="screen shot 2018-04-02 at 8 13 42 am" src="https://user-images.githubusercontent.com/2193314/38201625-cba73bb6-364d-11e8-87bc-882df4fe1135.png">

FYI @AlexandrePetit-Pas @parisk

**Comment by Tyriar** [comment]
@circuitry2 should be fixed now

**Comment by staminna** [comment]
@Tyriar I still getting same as circuitry2, commented [on 2 Apr 2018], the OP.

I cloned the main repository just now and I tried
Using node 18 and 14, on Macos 10.15.7. 

$ npm i

> node-pty@0.10.1 install /Users/myuser/smartdev/xterm.js/node_modules/node-pty
> node scripts/install.js

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> playwright@1.22.2 install /Users/myuser/smartdev/xterm.js/node_modules/playwright
> node install.js


> node-pty@0.10.1 postinstall /Users/myuser/smartdev/xterm.js/node_modules/node-pty
> node scripts/post-install.js


> xterm@4.18.0 prepare /Users/myuser/smartdev/xterm.js
> npm run setup


> xterm@4.18.0 presetup /Users/muser/smartdev/xterm.js
> node ./bin/install-addons.js

pulling addon dependencies...
Skipped xterm-addon-attach
Skipped xterm-addon-fit
Preparing xterm-addon-ligatures
Skipped xterm-addon-search
Skipped xterm-addon-serialize
Skipped xterm-addon-unicode11
Skipped xterm-addon-web-links
Skipped xterm-addon-webgl

> xterm@4.18.0 setup /Users/myuser/smartdev/xterm.js
> npm run build


> xterm@4.18.0 build /Users/myuser/smartdev/xterm.js
> tsc -b ./tsconfig.all.json

```
../../node_modules/xterm/typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:434:14 - error TS2687: All declarations of 'element' must have identical modifiers.

434     readonly element: HTMLElement | undefined;
                 ~~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:448:5 - error TS2687: All declarations of 'marker' must have identical modifiers.

448     marker: IMarker;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:454:5 - error TS2687: All declarations of 'anchor' must have identical modifiers.

454     anchor?: 'right' | 'left';
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:459:5 - error TS2687: All declarations of 'x' must have identical modifiers.

459     x?: number;
        ~

../../node_modules/xterm/typings/xterm.d.ts:466:5 - error TS2687: All declarations of 'width' must have identical modifiers.

466     width?: number;
        ~~~~~

../../node_modules/xterm/typings/xterm.d.ts:472:5 - error TS2687: All declarations of 'height' must have identical modifiers.

472     height?: number;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:650:16 - error TS2300: Duplicate identifier 'Terminal'.

650   export class Terminal implements IDisposable {
                   ~~~~~~~~

  typings/xterm.d.ts:700:16
    700   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

typings/xterm.d.ts:442:5 - error TS2687: All declarations of 'element' must have identical modifiers.

442     element: HTMLElement | undefined;
        ~~~~~~~

typings/xterm.d.ts:469:14 - error TS2687: All declarations of 'marker' must have identical modifiers.

469     readonly marker: IMarker;
                 ~~~~~~

typings/xterm.d.ts:475:14 - error TS2687: All declarations of 'anchor' must have identical modifiers.

475     readonly anchor?: 'right' | 'left';
                 ~~~~~~

typings/xterm.d.ts:480:14 - error TS2687: All declarations of 'x' must have identical modifiers.

480     readonly x?: number;
                 ~

typings/xterm.d.ts:486:14 - error TS2687: All declarations of 'width' must have identical modifiers.

486     readonly width?: number;
                 ~~~~~

typings/xterm.d.ts:491:14 - error TS2687: All declarations of 'height' must have identical modifiers.

491     readonly height?: number;
                 ~~~~~~

typings/xterm.d.ts:700:16 - error TS2300: Duplicate identifier 'Terminal'.

700   export class Terminal implements IDisposable {
                   ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:650:16
    650   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:434:14 - error TS2687: All declarations of 'element' must have identical modifiers.

434     readonly element: HTMLElement | undefined;
                 ~~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:448:5 - error TS2687: All declarations of 'marker' must have identical modifiers.

448     marker: IMarker;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:454:5 - error TS2687: All declarations of 'anchor' must have identical modifiers.

454     anchor?: 'right' | 'left';
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:459:5 - error TS2687: All declarations of 'x' must have identical modifiers.

459     x?: number;
        ~

../../node_modules/xterm/typings/xterm.d.ts:466:5 - error TS2687: All declarations of 'width' must have identical modifiers.

466     width?: number;
        ~~~~~

../../node_modules/xterm/typings/xterm.d.ts:472:5 - error TS2687: All declarations of 'height' must have identical modifiers.

472     height?: number;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:650:16 - error TS2300: Duplicate identifier 'Terminal'.

650   export class Terminal implements IDisposable {
                   ~~~~~~~~

  typings/xterm.d.ts:700:16
    700   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

typings/xterm.d.ts:442:5 - error TS2687: All declarations of 'element' must have identical modifiers.

442     element: HTMLElement | undefined;
        ~~~~~~~

typings/xterm.d.ts:469:14 - error TS2687: All declarations of 'marker' must have identical modifiers.

469     readonly marker: IMarker;
                 ~~~~~~

typings/xterm.d.ts:475:14 - error TS2687: All declarations of 'anchor' must have identical modifiers.

475     readonly anchor?: 'right' | 'left';
                 ~~~~~~

typings/xterm.d.ts:480:14 - error TS2687: All declarations of 'x' must have identical modifiers.

480     readonly x?: number;
                 ~

typings/xterm.d.ts:486:14 - error TS2687: All declarations of 'width' must have identical modifiers.

486     readonly width?: number;
                 ~~~~~

typings/xterm.d.ts:491:14 - error TS2687: All declarations of 'height' must have identical modifiers.

491     readonly height?: number;
                 ~~~~~~

typings/xterm.d.ts:700:16 - error TS2300: Duplicate identifier 'Terminal'.

700   export class Terminal implements IDisposable {
                   ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:650:16
    650   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

error TS2688: Cannot find type definition file for '../../../out-test/api/TestUtils'.
  The file is in the program because:
    Entry point of type library '../../../out-test/api/TestUtils' specified in compilerOptions

  addons/xterm-addon-attach/test/tsconfig.json:16:7
    16       "../../../out-test/api/TestUtils"
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.

../../node_modules/xterm/typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:434:14 - error TS2687: All declarations of 'element' must have identical modifiers.

434     readonly element: HTMLElement | undefined;
                 ~~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:448:5 - error TS2687: All declarations of 'marker' must have identical modifiers.

448     marker: IMarker;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:454:5 - error TS2687: All declarations of 'anchor' must have identical modifiers.

454     anchor?: 'right' | 'left';
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:459:5 - error TS2687: All declarations of 'x' must have identical modifiers.

459     x?: number;
        ~

../../node_modules/xterm/typings/xterm.d.ts:466:5 - error TS2687: All declarations of 'width' must have identical modifiers.

466     width?: number;
        ~~~~~

../../node_modules/xterm/typings/xterm.d.ts:472:5 - error TS2687: All declarations of 'height' must have identical modifiers.

472     height?: number;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:650:16 - error TS2300: Duplicate identifier 'Terminal'.

650   export class Terminal implements IDisposable {
                   ~~~~~~~~

  typings/xterm.d.ts:700:16
    700   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

typings/xterm.d.ts:442:5 - error TS2687: All declarations of 'element' must have identical modifiers.

442     element: HTMLElement | undefined;
        ~~~~~~~

typings/xterm.d.ts:469:14 - error TS2687: All declarations of 'marker' must have identical modifiers.

469     readonly marker: IMarker;
                 ~~~~~~

typings/xterm.d.ts:475:14 - error TS2687: All declarations of 'anchor' must have identical modifiers.

475     readonly anchor?: 'right' | 'left';
                 ~~~~~~

typings/xterm.d.ts:480:14 - error TS2687: All declarations of 'x' must have identical modifiers.

480     readonly x?: number;
                 ~

typings/xterm.d.ts:486:14 - error TS2687: All declarations of 'width' must have identical modifiers.

486     readonly width?: number;
                 ~~~~~

typings/xterm.d.ts:491:14 - error TS2687: All declarations of 'height' must have identical modifiers.

491     readonly height?: number;
                 ~~~~~~

typings/xterm.d.ts:700:16 - error TS2300: Duplicate identifier 'Terminal'.

700   export class Terminal implements IDisposable {
                   ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:650:16
    650   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

error TS2688: Cannot find type definition file for '../../../out-test/api/TestUtils'.
  The file is in the program because:
    Entry point of type library '../../../out-test/api/TestUtils' specified in compilerOptions

  addons/xterm-addon-fit/test/tsconfig.json:16:7
    16       "../../../out-test/api/TestUtils"
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.

../../node_modules/xterm/typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:434:14 - error TS2687: All declarations of 'element' must have identical modifiers.

434     readonly element: HTMLElement | undefined;
                 ~~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:448:5 - error TS2687: All declarations of 'marker' must have identical modifiers.

448     marker: IMarker;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:454:5 - error TS2687: All declarations of 'anchor' must have identical modifiers.

454     anchor?: 'right' | 'left';
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:459:5 - error TS2687: All declarations of 'x' must have identical modifiers.

459     x?: number;
        ~

../../node_modules/xterm/typings/xterm.d.ts:466:5 - error TS2687: All declarations of 'width' must have identical modifiers.

466     width?: number;
        ~~~~~

../../node_modules/xterm/typings/xterm.d.ts:472:5 - error TS2687: All declarations of 'height' must have identical modifiers.

472     height?: number;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:650:16 - error TS2300: Duplicate identifier 'Terminal'.

650   export class Terminal implements IDisposable {
                   ~~~~~~~~

  typings/xterm.d.ts:700:16
    700   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

typings/xterm.d.ts:442:5 - error TS2687: All declarations of 'element' must have identical modifiers.

442     element: HTMLElement | undefined;
        ~~~~~~~

typings/xterm.d.ts:469:14 - error TS2687: All declarations of 'marker' must have identical modifiers.

469     readonly marker: IMarker;
                 ~~~~~~

typings/xterm.d.ts:475:14 - error TS2687: All declarations of 'anchor' must have identical modifiers.

475     readonly anchor?: 'right' | 'left';
                 ~~~~~~

typings/xterm.d.ts:480:14 - error TS2687: All declarations of 'x' must have identical modifiers.

480     readonly x?: number;
                 ~

typings/xterm.d.ts:486:14 - error TS2687: All declarations of 'width' must have identical modifiers.

486     readonly width?: number;
                 ~~~~~

typings/xterm.d.ts:491:14 - error TS2687: All declarations of 'height' must have identical modifiers.

491     readonly height?: number;
                 ~~~~~~

typings/xterm.d.ts:700:16 - error TS2300: Duplicate identifier 'Terminal'.

700   export class Terminal implements IDisposable {
                   ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:650:16
    650   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

error TS2688: Cannot find type definition file for '../../../out-test/api/TestUtils'.
  The file is in the program because:
    Entry point of type library '../../../out-test/api/TestUtils' specified in compilerOptions

  addons/xterm-addon-search/test/tsconfig.json:16:7
    16       "../../../out-test/api/TestUtils"
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.

../../node_modules/xterm/typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

../../node_modules/xterm/typings/xterm.d.ts:434:14 - error TS2687: All declarations of 'element' must have identical modifiers.

434     readonly element: HTMLElement | undefined;
                 ~~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:448:5 - error TS2687: All declarations of 'marker' must have identical modifiers.

448     marker: IMarker;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:454:5 - error TS2687: All declarations of 'anchor' must have identical modifiers.

454     anchor?: 'right' | 'left';
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:459:5 - error TS2687: All declarations of 'x' must have identical modifiers.

459     x?: number;
        ~

../../node_modules/xterm/typings/xterm.d.ts:466:5 - error TS2687: All declarations of 'width' must have identical modifiers.

466     width?: number;
        ~~~~~

../../node_modules/xterm/typings/xterm.d.ts:472:5 - error TS2687: All declarations of 'height' must have identical modifiers.

472     height?: number;
        ~~~~~~

../../node_modules/xterm/typings/xterm.d.ts:650:16 - error TS2300: Duplicate identifier 'Terminal'.

650   export class Terminal implements IDisposable {
                   ~~~~~~~~

  typings/xterm.d.ts:700:16
    700   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

typings/xterm.d.ts:16:15 - error TS2300: Duplicate identifier 'FontWeight'.

16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                 ~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:16:15
    16   export type FontWeight = 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | number;
                     ~~~~~~~~~~
    'FontWeight' was also declared here.

typings/xterm.d.ts:21:15 - error TS2300: Duplicate identifier 'LogLevel'.

21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                 ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:21:15
    21   export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';
                     ~~~~~~~~
    'LogLevel' was also declared here.

typings/xterm.d.ts:26:15 - error TS2300: Duplicate identifier 'RendererType'.

26   export type RendererType = 'dom' | 'canvas';
                 ~~~~~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:26:15
    26   export type RendererType = 'dom' | 'canvas';
                     ~~~~~~~~~~~~
    'RendererType' was also declared here.

typings/xterm.d.ts:442:5 - error TS2687: All declarations of 'element' must have identical modifiers.

442     element: HTMLElement | undefined;
        ~~~~~~~

typings/xterm.d.ts:469:14 - error TS2687: All declarations of 'marker' must have identical modifiers.

469     readonly marker: IMarker;
                 ~~~~~~

typings/xterm.d.ts:475:14 - error TS2687: All declarations of 'anchor' must have identical modifiers.

475     readonly anchor?: 'right' | 'left';
                 ~~~~~~

typings/xterm.d.ts:480:14 - error TS2687: All declarations of 'x' must have identical modifiers.

480     readonly x?: number;
                 ~

typings/xterm.d.ts:486:14 - error TS2687: All declarations of 'width' must have identical modifiers.

486     readonly width?: number;
                 ~~~~~

typings/xterm.d.ts:491:14 - error TS2687: All declarations of 'height' must have identical modifiers.

491     readonly height?: number;
                 ~~~~~~

typings/xterm.d.ts:700:16 - error TS2300: Duplicate identifier 'Terminal'.

700   export class Terminal implements IDisposable {
                   ~~~~~~~~

  ../../node_modules/xterm/typings/xterm.d.ts:650:16
    650   export class Terminal implements IDisposable {
                       ~~~~~~~~
    'Terminal' was also declared here.

addons/xterm-addon-web-links/test/WebLinksAddon.api.ts:7:65 - error TS2307: Cannot find module '../../../out-test/api/TestUtils' or its corresponding type declarations.

7 import { openTerminal, pollFor, writeSync, launchBrowser } from '../../../out-test/api/TestUtils';
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 104 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@4.18.0 build: `tsc -b ./tsconfig.all.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xterm@4.18.0 build `script.`
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2022-06-17T14_36_41_549Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@4.18.0 setup: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xterm@4.18.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2022-06-17T14_36_41_576Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@4.18.0 prepare: `npm run setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xterm@4.18.0 prepare script.
```

**Comment by Tyriar** [comment]
Try deleting `out`/`out-test` and running `yarn watch`

**Comment by mdeneen** [comment]
This is still happening, for me with the following versions:

node: v18.16.0
npm: 9.5.1
yarn: 1.22.19
tsc: Version 4.7.4
webpack: 5.61.0
webpack-cli: 4.9.1

I have a feeling that it has to do with tsc, but I don't see where I'm going wrong.

**Comment by mdeneen** [comment]
I'm good, I must have had something stale in my tree as I was able to build after cloning again.
